/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_greycheatinglab_LazencaS */

#ifndef _Included_com_greycheatinglab_LazencaS
#define _Included_com_greycheatinglab_LazencaS
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
